<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8３．.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <DefineConstants>USE_SKIA</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.150.0" />
  </ItemGroup>

</Project>