<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
<Version>3.7.1</Version>
<AssemblyVersion>3.7.1</AssemblyVersion>
<FileVersion>3.7.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.150.0" />
  </ItemGroup>

</Project>